src/apps/strains/urls.py
from django.urls import path

from . import views

app_name = "strains"

urlpatterns = [
    path("", views.StrainListView.as_view(), name="list"),
    path("<slug:slug>/", views.StrainDetailView.as_view(), name="detail"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('censorship/', include('censorship.urls', namespace='censorship')),
    path('', include('strains.urls', namespace='strains')),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/strains/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _


class Strain(models.Model):
    TYPES = (
        (0, _("Сатива")),
        (1, _("Индика")),
        (2, _("Гибрид")),
    )

    DIFFICULTY = (
        (0, _("Легкая")),
        (1, _("Средняя")),
        (2, _("Высокая")),
    )

    HEIGHT = (
        (0, "< 30"),
        (1, "30 - 78"),
        (2, "> 78"),
    )

    CROP = (
        (0, "0.5 - 1"),
        (1, "1 - 3"),
        (2, "3 - 6"),
    )

    FLOWERING = (
        (0, "7 - 9"),
        (1, "10 - 12"),
        (2, "> 12"),
    )
    icon = models.CharField(max_length=50, verbose_name=_("Иконка"), default="🌿")
    name = models.CharField(max_length=255, verbose_name=_("Название сорта"))
    slug = models.SlugField(verbose_name=_("Slug"))
    description = models.TextField(blank=True, verbose_name=_("Описание"), null=True)
    type = models.IntegerField(
        choices=TYPES, verbose_name=_("Тип"), blank=True, null=True
    )
    thc = models.CharField(max_length=255, verbose_name=_("ТГК"), blank=True, null=True)
    cbd = models.CharField(max_length=255, verbose_name=_("КБД"), blank=True, null=True)
    difficulty = models.IntegerField(
        choices=DIFFICULTY,
        verbose_name=_("Сложность выращивания"),
        blank=True,
        null=True,
    )
    height = models.IntegerField(
        choices=HEIGHT, verbose_name=_("Высота растения"), blank=True, null=True
    )
    crop = models.IntegerField(
        choices=CROP, verbose_name=_("Урожайность"), blank=True, null=True
    )
    flowering = models.IntegerField(
        choices=FLOWERING, verbose_name=_("Время цветения"), blank=True, null=True
    )
    parents = models.CharField(
        max_length=255, verbose_name=_("Генетика"), blank=True, null=True
    )

    class Meta:
        verbose_name = _("Сорт")
        verbose_name_plural = _("Сорта")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.name)
        super().save(*args, **kwargs)

src/apps/strains/views.py
from django.db.models import Min, Max
from django.views.generic import DetailView
from django_filters.views import FilterView
from el_pagination.views import AjaxListView

from strains.constants import STRAIN_FILTER_DATA
from strains.filters import StrainFilter
from strains.models import Strain


class StrainListView(FilterView, AjaxListView):
    context_object_name = "strains"
    template_name = "strains/strain_list.html"
    page_template = "strains/strain_list_page.html"
    filterset_class = StrainFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filters"] = STRAIN_FILTER_DATA
        context["thc"] = Strain.objects.all().aggregate(Min("thc"), Max("thc"))
        return context


class StrainDetailView(DetailView):
    model = Strain
    context_object_name = "strain"
    template_name = "strains/strain_detail.html"
    slug_url_kwarg = "slug"
    slug_field = "slug"

src/apps/strains/templates/strains/strain_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="breadcrumbs">
        <a href="{% url 'strains:list' %}">Все сорта</a> / <span class="text-secondary">{{ strain.name }}</span>
    </div>
    <h1>{{ strain.name }}</h1>
    <p>{{ strain.icon }}</p>
    <p>{{ strain.get_type_display }}</p>
    <p>ТГК: {{ strain.thc }}%</p>
    <p>{{ strain.description }}</p>
    <h4>Информация о выращивании</h4>
    <ul>
        <li>Сложность выращивания: {{ strain.get_difficulty_display }}</li>
        <li>Высота растения: {{ strain.get_height_display }}</li>
        <li>Урожайность: {{ strain.get_crop_display }}</li>
        <li>Цветение: {{ strain.get_flowering_display }} недель</li>
        <li>Генетика: {{ strain.parents }}</li>
    </ul>
{% endblock content %}

src/apps/strains/templates/strains/strain_filter.html
{% load getlist %}
{% load getparam %}

<form class="mt-3">
    <p>
        <label for="amount">ТГК:</label>
        <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
    </p>

    <div id="slider-range"></div>

    <input type="hidden"
           name="thc_min"
           id="thc-min"
           data-thc="{{ thc.thc__min }}"
           value="{{ request.GET|getparam:'thc_min' }}"
    >
    <input type="hidden"
           name="thc_max"
           id="thc-max"
           data-thc="{{ thc.thc__max }}"
           value="{{ request.GET|getparam:'thc_max' }}"
    >

    {% for filter in filters %}
        <div class="form-group mt-3">
            <label>{{ filter.label }}</label>
            <div>
                {% for option in filter.options %}
                    <div class="form-check form-check-inline">
                        <input class="form-check-input"
                               type="checkbox"
                               id="{{ filter.name }}-{{ option.value }}"
                               name="{{ filter.name }}"
                               value={{ option.value }}
                                       {% if option.value in request.GET|getlist:filter.name %}checked{% endif %}
                        >
                        <label
                                class="form-check-label"
                                for="{{ filter.name }}-{{ option.value }}"
                        >
                            {{ option.label }}
                        </label>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Применить фильтр</button>
    <a href="{% url 'strains:list' %}" type="submit" class="btn btn-outline-primary">Сбросить фильтр</a>
</form>

src/apps/strains/templates/strains/strain_list.html
{% extends 'base.html' %}
{% load el_pagination_tags %}
{% load static %}
{% load sass_tags %}

{% block css %}
    {{ block.super }}
    <link href="{% sass_src 'strains/css/index.scss' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet" type="text/css"/>
{% endblock css %}

{% block content %}
    {% include "strains/strain_filter.html" %}
    <div class="row mb-3">
        {% include "strains/strain_list_page.html" %}
    </div>
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'strains/js/index.js' %}"></script>
    <script src="{% static 'el-pagination/js/el-pagination.js' %}"></script>
    <script>$.endlessPaginate();</script>
{% endblock js %}

src/apps/strains/templates/strains/strain_list_page.html
{% load el_pagination_tags %}

{% paginate strains %}
{% for strain in strains %}
    <div class="col-sm-6 mt-3">
        <a class="card" href="{% url 'strains:detail' strain.slug %}">
            <div class="card-body">
                <p>{{ strain.icon }}</p>
                <h5 class="card-title">{{ strain.name }}</h5>
                <p class="card-text">{{ strain.get_type_display }}</p>
                <p class="card-text">{{ strain.thc }}%</p>
            </div>
        </a>
    </div>
{% endfor %}
{% show_more "Загрузить еще" %}